name: 'AWS Device Farm'
description: 'Run Tests on AWS Device Farm'
inputs:
  accessKeyId:
    description: 'AWS accessKeyId'
    required: true
  secretAccessKeyId:
    description: 'AWS secretAccessKeyId'
    required: true
  region:
    description: 'AWS region'
    default: 'us-west-2'
outputs:
  projects:
    description: 'A list of device farm projects'
runs:
  using: 'node12'
  main: 'src/index.js'