name: 'AWS Device Farm'
description: 'Run Tests on AWS Device Farm'
inputs:
  accessKeyId:
    description: 'AWS accessKeyId'
    required: true
  secretAccessKeyId:
    description: 'AWS secretAccessKeyId'
    required: true
  region:
    description: 'AWS region'
    default: 'us-west-2'
  projectName:
    description: 'AWS Device Farm project name'
    required: true
  devicePoolName:
    description: 'AWS Device Pool name'
    required: true
outputs:
  project:
    description: 'The AWS Device farm project'
  devicePool:
    description: 'The AWS Device pool'
runs:
  using: 'node12'
  main: 'src/index.js'
