name: 'AWS Device Farm'
description: 'Run Tests on AWS Device Farm'
inputs:
  accessKeyId:
    description: 'AWS accessKeyId'
    required: true
  secretAccessKeyId:
    description: 'AWS secretAccessKeyId'
    required: true
  region:
    description: 'AWS region'
    default: 'us-west-2'
  projectName:
    description: 'AWS Device Farm project name'
    required: true
  devicePoolName:
    description: 'AWS Device Pool name'
    required: true
  appBinaryPath:
    description: 'Application binary filesystem path'
    required: true
  testPackagePath:
    description: 'Test scripts package filesystem path'
    required: true
  testPackageType:
    description: 'Test scripts package type. Must be one of _TEST_PACKAGE types defined in https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DeviceFarm.html#createUpload-property'
    required: true
  testSpecPath:
    description: 'Test environment spec filesystem path'
    required: true
  

outputs:
  testRunResults:
    description: 'Test run results JSON output. See https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_GetRun.html'
  testRunConsoleUrl:
    description: 'AWS Device Farm console test run results URL'
runs:
  using: 'node12'
  main: 'src/index.js'
