name: 'AWS Device Farm'
description: 'Run Tests on AWS Device Farm'
inputs:
  accessKeyId:
    description: 'AWS accessKeyId'
    required: true
  secretAccessKeyId:
    description: 'AWS secretAccessKeyId'
    required: true
  region:
    description: 'AWS region'
    default: 'us-west-2'
  projectName:
    description: 'AWS Device Farm project name'
    required: true
  devicePoolName:
    description: 'AWS Device Pool name'
    required: true
  appBinaryPath:
    description: 'Application binary filesystem path'
    required: true
  testPackagePath:
    description: 'Test scripts package filesystem path'
    required: true
  testPackageType:
    description: 'Test scripts package type. Must be one of _TEST_PACKAGE types defined in https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DeviceFarm.html#createUpload-property'
    required: true

outputs:
  project:
    description: 'The AWS Device farm project'
  devicePool:
    description: 'The AWS Device pool'
  appUploadResults:
    description: 'App upload response'
runs:
  using: 'node12'
  main: 'src/index.js'
